CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    wallet VARCHAR(255) NOT NULL,
    balance FLOAT DEFAULT 0,
    currency VARCHAR(50) DEFAULT 'eth',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);